# Generated by Django 5.0.1 on 2024-01-27 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lib_app', '0002_authordetails'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AuthorDetails',
        ),
    ]
