# Generated by Django 5.0.1 on 2024-01-27 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lib_app', '0003_delete_authordetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='status',
            field=models.CharField(default=True),
        ),
        migrations.AddField(
            model_name='book',
            name='status',
            field=models.CharField(default=True),
        ),
    ]
